name: mooren
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_local_notifications: ^4.0.1+2
  flutter_launcher_icons: ^0.8.1
  flutter_image_compress: ^0.7.0
  flutter_native_splash: ^0.3.2
  shared_preferences: ^0.5.12+4
  cached_network_image: ^2.3.1
  permission_handler: ^5.1.0+2
  firebase_messaging: ^7.0.3
  cloud_firestore: ^0.14.1+3
  firebase_storage: ^5.2.0
  firebase_auth: ^0.18.1+2
  image_picker: ^0.6.7+22
  email_validator: ^1.0.6
  firebase_core: ^0.5.0+1
  package_info: ^0.4.3+4
  path_provider: ^1.6.28
  animations: ^1.1.2
  provider: ^4.3.3
  shimmer: ^1.1.2
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/img/logo.png" 
  android: true
  ios: true

flutter_native_splash:
  image: "assets/img/logo.png"
  color: "f5f5f5"
  android_disable_fullscreen: true
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/img/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  fonts:
    - family: 'SF Pro Reguler'
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-RegularItalic.otf
    
    - family: 'SF Pro Medium'
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
        - asset: assets/fonts/SF-Pro-Display-MediumItalic.otf

    - family: 'SF Pro Semibold'
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
        - asset: assets/fonts/SF-Pro-Display-SemiboldItalic.otf

    - family: 'SF Pro Thin'
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
        - asset: assets/fonts/SF-Pro-Display-ThinItalic.otf

    - family: 'SF Pro Light'
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Light.otf
        - asset: assets/fonts/SF-Pro-Display-LightItalic.otf

    - family: 'SF Pro Bold'
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
        - asset: assets/fonts/SF-Pro-Display-BoldItalic.otf

    - family: 'SF Pro Ultralight'
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
        - asset: assets/fonts/SF-Pro-Display-UltralightItalic.otf

    - family: 'SF Pro Reguler Round'
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.otf
    
    - family: 'SF Pro Medium Round'
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Medium.otf

    - family: 'SF Pro Semibold Round'
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Semibold.otf

    - family: 'SF Pro Thin Round'
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Thin.otf

    - family: 'SF Pro Light Round'
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Light.otf

    - family: 'SF Pro Bold Round'
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Bold.otf

    - family: 'SF Pro Ultralight Round'
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Ultralight.otf

    - family: 'iconsax'
      fonts:
        - asset: assets/fonts/iconsax.ttf
        
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
